apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gensynth-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin ~ '^http:\/\/{{ required "hostname is required" .Values.hostname }}(\.honeywell\.com)?') {
        set $allow_origin $http_origin;
      }
      add_header 'Access-Control-Allow-Origin' "$allow_origin";
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, PATCH, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
spec:
  rules:
  - host: {{ required "hostname is required" .Values.hostname }}-api{{ .Values.jobIndex }}
    http:
      paths:
      - backend:
          serviceName: gensynth-api
          servicePort: 3000
        path: /(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gensynth-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ required "hostname is required" .Values.hostname }}{{ .Values.jobIndex }}
    http:
      paths:
      - backend:
          serviceName: gensynth-web
          servicePort: 80
        path: /(.*)
  - host: {{ required "hostname is required" .Values.hostname }}{{ .Values.jobIndex }}.honeywell.com
    http:
      paths:
        - backend:
            serviceName: gensynth-web
            servicePort: 80
          path: /(.*)
